os: linux
dist: xenial
language: golang
sudo: true
before_install:
  - sudo add-apt-repository ppa:masterminds/glide
  - sudo apt-get update
  - sudo apt-get install -y glide
install:
  - glide install
script:
  - make test