os: linux
dist: xenial
language: go
go:
  - 1.11.x
sudo: true
install:
  - sudo add-apt-repository -y ppa:masterminds/glide
  - sudo apt-get update
  - sudo apt-get install -y glide
script:
  - make test