apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: scale-marketplace
  namespace: marketplace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: marketplace-cmd
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: External
      external:
        metricName: rpm
        targetAverageValue: 200
        metricSelector:
            matchLabels:
              appName: marketplace-prod
